#!/bin/sh

if ! cargo fmt -- --check 2>/dev/null; then
    echo "staged files not formatted. run \`cargo fmt\` to format them." && exit 1
fi

if ! cargo clippy --color always -- -D warnings; then
    echo "clippy failed" && exit 1
fi

if ! cargo test -q 2>&1; then
    echo "tests failed" && exit 1
fi

exit 0
